apiVersion: v1
kind: Service
metadata:
  labels:
    app: bookalbum_batch_3
  name: bookalbum_batch_3
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: bookalbum_batch_3

